production:
  adapter: mysql2
  database: openproject
  host: localhost
  username: openproject
  password: my_password
  encoding: utf8

development:
  adapter: mysql2
  database: openproject
  host: localhost
  username: openproject
  password: my_password
  encoding: utf8
